### ISSUE TITLE
BUG？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [jco2641/bspkrsCore#1]
Forge：1.10.2-forge1.10.2-12.18.2.2114
![qq 20161030150241](https://cloud.githubusercontent.com/assets/20567492/19834981/324b4dd8-9eb2-11e6-9647-3e5e884ca9c6.png)
![qq 20161030150410](https://cloud.githubusercontent.com/assets/20567492/19834982/324e1978-9eb2-11e6-9202-aa2bee79d087.png)
Not only is your problem, all BspkrsCore in Forge2114 will have this problem.
@jco2641 @BlueAnanas

**Comment by jco2641** [comment]
Caused by Forge max version annotation in the mcmod.info.
Corrected in 7.4.7 release.
Also updated to compile against forge 12.18.2.2116 and Oct 30 mcp mappings.
